version: '3'
services:
  seed_node:
    image: "datastax/dse-server:${DSE_VERSION}"
    environment:
      - DS_LICENSE=accept
      - DC=seed
    ports:
      - 9042:9042
      - 9142:9142
  search:
    image: "datastax/dse-server:${DSE_VERSION}"
    depends_on:
      - seed_node
    environment:
      - DS_LICENSE=accept
      - SEEDS=seed_node
      - DC=search
    command: -s
  analytics:
    image: "datastax/dse-server:${DSE_VERSION}"
    depends_on:
      - seed_node
    environment:
      - DS_LICENSE=accept
      - SEEDS=seed_node
      - DC=analytics
    command: -k
  searchanalytics:
    image: "datastax/dse-server:${DSE_VERSION}"
    depends_on:
      - seed_node
    environment:
      - DS_LICENSE=accept
      - SEEDS=seed_node
      - DC=searchanalytics
    command: -k -s
